// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BestWish: typeof import('./components/BestWish.vue')['default']
    BirthdayCake: typeof import('./components/BirthdayCake.vue')['default']
  }
}

export { }
